Repository UBC-MDS/SharpEdge, pull requests merged in 2025-01, with the labels that each got.

#12 Software structure
  .github/workflows/ci-cd.yml
  .gitignore
  .readthedocs.yml
  CHANGELOG.md
  CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/Makefile
  docs/changelog.md
  docs/conduct.md
  docs/conf.py
  docs/contributing.md
  docs/example.ipynb
  docs/index.md
  docs/make.bat
  docs/requirements.txt
  pyproject.toml
  src/sharpedge/__init__.py
  src/sharpedge/sharpedge.py
  tests/test_sharpedge.py
Labels: documentation

#20 docs: updated package functions usage in README.md
  README.md
Labels: documentation

#22 docs: reordered functions and updated the usage for flipping function in README.md
  README.md
Labels: documentation

#43 36 set up utility class skeleton
  src/sharpedge/_utils/utility.py
  tests/test_utility.py
Labels: enhancement

#48 Func test util image format
  src/sharpedge/_utils/utility.py
  tests/test_utility.py
Labels: tests

#54 add input image array shape check
  src/sharpedge/_utils/utility.py
Labels: enhancement

#55 test: use the try and except framework for the expected and edge cases.
  tests/test_utility.py
Labels: tests

#47 Func test util color range
  pyproject.toml
  src/sharpedge/_utils/utility.py
  tests/test_frame_image.py
  tests/test_utility.py
Labels: enhancement, tests

#65 Func test seam carving
  poetry.lock
  pyproject.toml
  src/sharpedge/seam_carving.py
  tests/test_image/seam_carve_input_1.png
  tests/test_image/seam_carve_input_2.png
  tests/test_image/seam_carve_input_3.png
  tests/test_image/seam_carve_output_1_1.png
  tests/test_image/seam_carve_output_1_2.png
  tests/test_image/seam_carve_output_1_3.png
  tests/test_image/seam_carve_output_2.png
  tests/test_image/seam_carve_output_3.png
  tests/test_seam_carving.py
Labels: tests

#60 Func test padding
  pyproject.toml
  src/sharpedge/frame_image.py
  tests/test_frame_image.py
Labels: enhancement, tests

#64 Func test color conv
  src/sharpedge/modulate_image.py
  tests/test_modulate_image.py
Labels: enhancement, tests

#74 feat: function commented code cleaned up and add in _input_checker
  src/sharpedge/frame_image.py
Labels: enhancement

#73 feat: add _input_checker to function
  src/sharpedge/modulate_image.py
Labels: enhancement

#77 Delete the unused load_image.py and display_image.py, update the README.md, and fix the poetry
  README.md
  tests/display_image.py
  tests/load_image.py
Labels: documentation

#79 fix: leave out the test case for single pixel image
  src/sharpedge/seam_carving.py
  tests/test_seam_carving.py
Labels: bug

#85 Switch back to direct calling of input checker to ensure full code coverage
  src/sharpedge/frame_image.py
  src/sharpedge/modulate_image.py
  src/sharpedge/pca_compression.py
  src/sharpedge/pooling_image.py
  src/sharpedge/reposition_image.py
Labels: enhancement

#101 Set up the structure of our documentation and example tutorial
  docs/conf.py
  docs/example.ipynb
  docs/first_things_first.ipynb
  docs/image_framing.ipynb
  docs/image_modulation.ipynb
  docs/image_pooling.ipynb
  docs/image_reposition.ipynb
  docs/index.md
  docs/pca_compression.ipynb
  docs/seam_carving.ipynb
  poetry.lock
  pyproject.toml
Labels: documentation, dependencies

#104 Func test color conv
  src/sharpedge/modulate_image.py
  tests/test_modulate_image.py
Labels: enhancement, tests

#105 feat: update function for more flexibility in customization
  src/sharpedge/frame_image.py
Labels: enhancement

#106 Func test color conv
  src/sharpedge/modulate_image.py
  tests/test_modulate_image.py
Labels: enhancement

#107 Docs padding
  docs/image_framing.ipynb
Labels: documentation

#108 Docs color conv
  docs/image_modulation.ipynb
Labels: documentation

#110 Docs seam carve
  docs/seam_carving.ipynb
  src/sharpedge/_utils/utility.py
  src/sharpedge/seam_carving.py
Labels: documentation

#121 Fix the NoSuchKernel exception on Read the Docs
  .readthedocs.yml
Labels: documentation

#123 Fix import error with the scikit-image package
  .readthedocs.yml
Labels: bug

#124 docs: add documentation status badge
  README.md
Labels: documentation

#126 Fix references in `index.md`
  CONDUCT.md
  docs/index.md
Labels: bug

#129 docs: rewrite the python ecosystem part in README.md
  README.md
Labels: documentation

#146 fix: Feedback addressed by Archer - Milestone 1 feedback on Software package project structure
  README.md
  src/sharpedge/__init__.py
  src/sharpedge/modulate_image.py
  tests/test_frame_image.py
  tests/test_modulate_image.py
  tests/test_pca_compression.py
  tests/test_pooling_image.py
  tests/test_reposition_image.py
  tests/test_seam_carving.py
Labels: enhancement
