Repository UBC-MDS/SharpEdge, pull requests merged in 2025-02, with the labels that each got.

#167 Peer review: add missing badges in `README.md`
  README.md
Labels: documentation

#160 peer review: `frame_image` documentation update
  docs/image_framing.ipynb
Labels: documentation

#162 Peer Review: seam_carve fix grammar mistake
  docs/image_seam_carving.ipynb
Labels: documentation

#157 fix: Feedback addressed by Jenny - `modulate_image`
  src/sharpedge/modulate_image.py
Labels: enhancement

#153 CHANGELOG.md updated to reflect correct versioning
  CHANGELOG.md
Labels: documentation

#173 fix: Feedback addressed by Archer - Added a note in the README to guide users to the documentation for examples
  README.md
Labels: documentation

#158 `frame_image` break down into intermediate functions
  src/sharpedge/frame_image.py
Labels: enhancement

#152 improve PCA function tutorial and docstring from peer review
  docs/image_pca_compression.ipynb
  src/sharpedge/pca_compression.py
Labels: documentation

#177 TA Feedback: tackle a lot of test cases
  tests/test_frame_image.py
  tests/test_modulate_image.py
Labels: tests

#179 build: change html theme to rtd (from press) as press has minial updates
  docs/conf.py
Labels: documentation

#178 docs: update examples section to meet numpy style for API reference
  src/sharpedge/modulate_image.py
Labels: documentation

#150 improve introduction tutorial from peer review
  docs/first_things_first.ipynb
  docs/img/cat2.jpeg
Labels: documentation
